#!/bin/bash 

### usb 3.0
#sudo -s
#cd /sys/bus/pci/drivers/xhci_hcd/
#for file in ????:??:??.? ; do
# echo -n "$file" > unbind
# echo -n "$file" > bind
#done


###usb 2.0

cd /sys/bus/pci/drivers/ehci-pci/
for file in ????:??:??.? ; do
 echo -n "$file" > unbind
 echo -n "$file" > bind
done
