# Don't print a new line at the start of the prompt
add_newline = false

[username]
show_always = true

[cmd_duration]
disabled = false

[directory]
truncation_length = 8

# Replace the "❯" symbol in the prompt with "➜"
# The name of the module we are configuring is "character"
[character]                            
success_symbol = "[❯](bold bright-green)" 


